namespace Microsoft.EntityFrameworkCore.Metadata;

/// <summary>
/// Identifies the Dameng database feature used to generate values for a property.
/// </summary>
public enum DamengValueGenerationStrategy
{
    /// <summary>
    /// No Dameng-specific value generation strategy is configured.
    /// </summary>
    None,

    /// <summary>
    /// Values are generated by a Dameng <c>IDENTITY</c> column.
    /// </summary>
    IdentityColumn,

    /// <summary>
    /// Values are generated by a Dameng sequence through its <c>NEXTVAL</c> member.
    /// </summary>
    Sequence,
}
